# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@netflix/nerror-1.1.3" = {
      name = "_at_netflix_slash_nerror";
      packageName = "@netflix/nerror";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@netflix/nerror/-/nerror-1.1.3.tgz";
        sha512 = "b+MGNyP9/LXkapreJzNUzcvuzZslj/RGgdVVJ16P2wSlYatfLycPObImqVJSmNAdyeShvNeM/pl3sVZsObFueg==";
      };
    };
    "@sentry/core-5.29.0" = {
      name = "_at_sentry_slash_core";
      packageName = "@sentry/core";
      version = "5.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/core/-/core-5.29.0.tgz";
        sha512 = "a1sZBJ2u3NG0YDlGvOTwUCWiNjhfmDtAQiKK1o6RIIbcrWy9TlSps7CYDkBP239Y3A4pnvohjEEKEP3v3L3LZQ==";
      };
    };
    "@sentry/hub-5.29.0" = {
      name = "_at_sentry_slash_hub";
      packageName = "@sentry/hub";
      version = "5.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/hub/-/hub-5.29.0.tgz";
        sha512 = "kcDPQsRG4cFdmqDh+TzjeO7lWYxU8s1dZYAbbl1J4uGKmhNB0J7I4ak4SGwTsXLY6fhbierxr6PRaoNojCxjPw==";
      };
    };
    "@sentry/minimal-5.29.0" = {
      name = "_at_sentry_slash_minimal";
      packageName = "@sentry/minimal";
      version = "5.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/minimal/-/minimal-5.29.0.tgz";
        sha512 = "nhXofdjtO41/caiF1wk1oT3p/QuhOZDYdF/b29DoD2MiAMK9IjhhOXI/gqaRpDKkXlDvd95fDTcx4t/MqqcKXA==";
      };
    };
    "@sentry/node-5.29.0" = {
      name = "_at_sentry_slash_node";
      packageName = "@sentry/node";
      version = "5.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/node/-/node-5.29.0.tgz";
        sha512 = "Jp32FsfkFSGVf81Hr26rGlgIwTg7Nx07mQ7rrnNuVasu6vD2aWBzUnohkkZDJ4gZRGjmk0MthukjX0RivDKcVQ==";
      };
    };
    "@sentry/tracing-5.29.0" = {
      name = "_at_sentry_slash_tracing";
      packageName = "@sentry/tracing";
      version = "5.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/tracing/-/tracing-5.29.0.tgz";
        sha512 = "2ZITUH7Eur7IkmRAd5gw8Xt2Sfc28btCnT7o2P2J8ZPD65e99ATqjxXPokx0+6zEkTsstIDD3mbyuwkpbuvuTA==";
      };
    };
    "@sentry/types-5.29.0" = {
      name = "_at_sentry_slash_types";
      packageName = "@sentry/types";
      version = "5.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/types/-/types-5.29.0.tgz";
        sha512 = "iDkxT/9sT3UF+Xb+JyLjZ5caMXsgLfRyV9VXQEiR2J6mgpMielj184d9jeF3bm/VMuAf/VFFqrHlcVsVgmrrMw==";
      };
    };
    "@sentry/utils-5.29.0" = {
      name = "_at_sentry_slash_utils";
      packageName = "@sentry/utils";
      version = "5.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/utils/-/utils-5.29.0.tgz";
        sha512 = "b2B1gshw2u3EHlAi84PuI5sfmLKXW1z9enMMhNuuNT/CoRp+g5kMAcUv/qYTws7UNnYSvTuVGuZG30v1e0hP9A==";
      };
    };
    "@types/color-name-1.1.1" = {
      name = "_at_types_slash_color-name";
      packageName = "@types/color-name";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/color-name/-/color-name-1.1.1.tgz";
        sha512 = "rr+OQyAjxze7GgWrSaJwydHStIhHq2lvY3BOC2Mj7KnzI7XK0Uw1TOOdI9lDoajEbSWLiYgoo4f1R51erQfhPQ==";
      };
    };
    "agent-base-6.0.0" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-6.0.0.tgz";
        sha512 = "j1Q7cSCqN+AwrmDd+pzgqc0/NpC655x2bUf5ZjRIO77DcNBFmh+OgRNzF6OKdCC9RSCb19fGd99+bhXFdkRNqw==";
      };
    };
    "ansi-escapes-4.3.1" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-4.3.1.tgz";
        sha512 = "JWF7ocqNrp8u9oqpgV+wH5ftbt+cfvv+PTjOvKLT3AdYly/LmORARfEVT1iyjwN+4MqE5UmVKoAdIBqeoCHgLA==";
      };
    };
    "ansi-regex-5.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.0.tgz";
        sha512 = "bY6fj56OUQ0hU1KjFNDQuJFezqKdrAyFdIevADiqrWHwSlbmBNMHp5ak2f40Pm8JTFyM2mqxkG6ngkHO11f/lg==";
      };
    };
    "ansi-styles-4.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.2.1.tgz";
        sha512 = "9VGjrMsG1vePxcSweQsN20KY/c4zN0h9fLjqAbwbPfahM3t+NL+M9HC8xeXG2I8pX5NoamTGNuomEUFI7fcUjA==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "asn1-0.2.4" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.4.tgz";
        sha512 = "jxwzQpLQjSmWXgwaCZE9Nz+glAG01yF1QnWgbhGwHI5A6FRIEY6IVqtHhIepHqI7/kyEyQEagBC5mBEFlIYvdg==";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "axios-0.21.1" = {
      name = "axios";
      packageName = "axios";
      version = "0.21.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/axios/-/axios-0.21.1.tgz";
        sha512 = "dKQiRHxGD9PPRIUNIWvZhPTPpl1rf/OxTYKsqKUDjBwYylTvV7SjSHJb9ratfyzM6wCdLCOYLzs73qpg5c4iGA==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "batch-promises-0.0.3" = {
      name = "batch-promises";
      packageName = "batch-promises";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/batch-promises/-/batch-promises-0.0.3.tgz";
        sha1 = "04b850fe6847c7aff05f3cca41045932430b1c32";
      };
    };
    "bcrypt-pbkdf-1.0.2" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz";
        sha1 = "a4301d389b6a43f9b67ff3ca11a3f6637e360e9e";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "brembo-2.0.4" = {
      name = "brembo";
      packageName = "brembo";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/brembo/-/brembo-2.0.4.tgz";
        sha512 = "XF4b6Xc+xpCRTzURhjWAMfHcZLp3TCslFlVsNK3I5ZxB9WnfF1lyuFZYSWL5acKmAUjAKKnzt6ADYrMqfj8vSQ==";
      };
    };
    "bufferutil-4.0.2" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.2.tgz";
        sha512 = "AtnG3W6M8B2n4xDQ5R+70EXvOpnXsFYg/AK2yTZd+HQ/oxAdz+GI+DvjmhBw3L0ole+LJ0ngqY4JMbDzkfNzhA==";
      };
    };
    "bunyan-1.8.12" = {
      name = "bunyan";
      packageName = "bunyan";
      version = "1.8.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/bunyan/-/bunyan-1.8.12.tgz";
        sha1 = "f150f0f6748abdd72aeae84f04403be2ef113797";
      };
    };
    "chalk-4.1.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.0.tgz";
        sha512 = "qwx12AxXe2Q5xQ43Ac//I6v5aXTipYrSESdOgzrN+9XjgEpyjpKuvSGaN4qE93f7TQTlerQQ8S+EQ0EyDoVL1A==";
      };
    };
    "chardet-0.7.0" = {
      name = "chardet";
      packageName = "chardet";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chardet/-/chardet-0.7.0.tgz";
        sha512 = "mT8iDcrh03qDGRRmoA2hmBJnxpllMR+0/0qlzjqZES6NdiWDcZkCNAk4rPFZ9Q85r27unkiNNg8ZOiwZXBHwcA==";
      };
    };
    "charenc-0.0.2" = {
      name = "charenc";
      packageName = "charenc";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/charenc/-/charenc-0.0.2.tgz";
        sha1 = "c0a1d2f3a7092e03774bfa83f14c0fc5790a8667";
      };
    };
    "cli-cursor-3.1.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-3.1.0.tgz";
        sha512 = "I/zHAwsKf9FqGoXM4WWRACob9+SNukZTd94DWF57E4toouRulbCxcUh6RKUEOQlYTHJnzkPMySvPNaaSLNfLZw==";
      };
    };
    "cli-width-3.0.0" = {
      name = "cli-width";
      packageName = "cli-width";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-width/-/cli-width-3.0.0.tgz";
        sha512 = "FxqpkPPwu1HjuN93Omfm4h8uIanXofW0RxVEW3k5RKx+mJJYSthzNhp32Kzxxy3YAEZ/Dc/EWN1vZRY0+kOhbw==";
      };
    };
    "cliui-7.0.4" = {
      name = "cliui";
      packageName = "cliui";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-7.0.4.tgz";
        sha512 = "OcRE68cOsVMXp1Yvonl/fzkQOyjLSu/8bhPDfQt0e0/Eb283TKP20Fs2MqoPsr9SwA595rRCA+QMzYc9nBP+JQ==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "cookie-0.4.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.4.1.tgz";
        sha512 = "ZwrFkGJxUR3EIoXtO+yVE69Eb7KlixbaeAWfBQB9vVsNn/o+Yw69gBWSSDK825hQNdN+wF8zELf3dFNl/kxkUA==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "crypt-0.0.2" = {
      name = "crypt";
      packageName = "crypt";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypt/-/crypt-0.0.2.tgz";
        sha1 = "88d7ff7ec0dfb86f713dc87bbb42d044d3e6c41b";
      };
    };
    "csv-5.3.2" = {
      name = "csv";
      packageName = "csv";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/csv/-/csv-5.3.2.tgz";
        sha512 = "odDyucr9OgJTdGM2wrMbJXbOkJx3nnUX3Pt8SFOwlAMOpsUQlz1dywvLMXJWX/4Ib0rjfOsaawuuwfI5ucqBGQ==";
      };
    };
    "csv-generate-3.2.4" = {
      name = "csv-generate";
      packageName = "csv-generate";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/csv-generate/-/csv-generate-3.2.4.tgz";
        sha512 = "qNM9eqlxd53TWJeGtY1IQPj90b563Zx49eZs8e0uMyEvPgvNVmX1uZDtdzAcflB3PniuH9creAzcFOdyJ9YGvA==";
      };
    };
    "csv-parse-4.10.1" = {
      name = "csv-parse";
      packageName = "csv-parse";
      version = "4.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/csv-parse/-/csv-parse-4.10.1.tgz";
        sha512 = "gdDJVchi0oSLIcYXz1H/VSgLE6htHDqJyFsRU/vTkQgmVOZ3S0IR2LXnNbWUYG7VD76dYVwdfBLyx8AX9+An8A==";
      };
    };
    "csv-stringify-5.5.0" = {
      name = "csv-stringify";
      packageName = "csv-stringify";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/csv-stringify/-/csv-stringify-5.5.0.tgz";
        sha512 = "G05575DSO/9vFzQxZN+Srh30cNyHk0SM0ePyiTChMD5WVt7GMTVPBQf4rtgMF6mqhNCJUPw4pN8LDe8MF9EYOA==";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-4.1.1" = {
      name = "debug";
      packageName = "debug";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz";
        sha512 = "pYAIzeRo8J6KPEaJ0VWOh5Pzkbw/RetuzehGM7QRRX5he4fPHx2rdKMB256ehJCkX+XRQm16eZLqLNS8RSZXZw==";
      };
    };
    "deepmerge-4.2.2" = {
      name = "deepmerge";
      packageName = "deepmerge";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deepmerge/-/deepmerge-4.2.2.tgz";
        sha512 = "FJ3UgI4gIl+PHZm53knsuSFpE+nESMr7M4v9QcgB7S63Kj/6WqMiFQJpBBYz1Pt+66bZpP3Q7Lye0Oo9MPKEdg==";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "detect-node-2.0.4" = {
      name = "detect-node";
      packageName = "detect-node";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-node/-/detect-node-2.0.4.tgz";
        sha512 = "ZIzRpLJrOj7jjP2miAtgqIfmzbxa4ZOr5jJc601zklsfEx9oTzmmj2nVpIPRpNlRTIh8lc1kyViIY7BWSGNmKw==";
      };
    };
    "dtrace-provider-0.8.8" = {
      name = "dtrace-provider";
      packageName = "dtrace-provider";
      version = "0.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/dtrace-provider/-/dtrace-provider-0.8.8.tgz";
        sha512 = "b7Z7cNtHPhH9EJhNNbbeqTcXB8LGFFZhq1PGgEvpeHlzd36bhbdTWoE/Ba/YguqpBSlAPKnARWhVlhunCMwfxg==";
      };
    };
    "ecc-jsbn-0.1.2" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.2.tgz";
        sha1 = "3a83a904e54353287874c564b7549386849a98c9";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "escape-regexp-component-1.0.2" = {
      name = "escape-regexp-component";
      packageName = "escape-regexp-component";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-regexp-component/-/escape-regexp-component-1.0.2.tgz";
        sha1 = "9c63b6d0b25ff2a88c3adbd18c5b61acc3b9faa2";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha1 = "41ae2eeb65efa62268aebfea83ac7d79299b0887";
      };
    };
    "ewma-2.0.1" = {
      name = "ewma";
      packageName = "ewma";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ewma/-/ewma-2.0.1.tgz";
        sha512 = "MYYK17A76cuuyvkR7MnqLW4iFYPEi5Isl2qb8rXiWpLiwFS9dxW/rncuNnjjgSENuVqZQkIuR4+DChVL4g1lnw==";
      };
    };
    "external-editor-3.1.0" = {
      name = "external-editor";
      packageName = "external-editor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/external-editor/-/external-editor-3.1.0.tgz";
        sha512 = "hMQ4CX1p1izmuLYyZqLMO/qGNw10wSv9QDCPfzXfyFrOaCSSoRfqE1Kf1s5an66J5JZC62NewG+mK49jOCtQew==";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "extsprintf-1.4.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.4.0.tgz";
        sha1 = "e2689f8f356fad62cca65a3a91c5df5f9551692f";
      };
    };
    "fast-decode-uri-component-1.0.1" = {
      name = "fast-decode-uri-component";
      packageName = "fast-decode-uri-component";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-decode-uri-component/-/fast-decode-uri-component-1.0.1.tgz";
        sha512 = "WKgKWg5eUxvRZGwW8FvfbaH7AXSh2cL+3j5fMGzUMCxWBJ3dV3a7Wz8y2f/uQ0e3B6WmodD3oS54jTQ9HVTIIg==";
      };
    };
    "figures-3.2.0" = {
      name = "figures";
      packageName = "figures";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figures/-/figures-3.2.0.tgz";
        sha512 = "yaduQFRKLXYOGgEn6AZau90j3ggSOyiqXU0F9JZfeXYhNa+Jk4X+s45A2zg5jns87GAFa34BBm2kXw4XpNcbdg==";
      };
    };
    "file-stream-rotator-0.5.7" = {
      name = "file-stream-rotator";
      packageName = "file-stream-rotator";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-stream-rotator/-/file-stream-rotator-0.5.7.tgz";
        sha512 = "VYb3HZ/GiAGUCrfeakO8Mp54YGswNUHvL7P09WQcXAJNSj3iQ5QraYSp3cIn1MUyw6uzfgN/EFOarCNa4JvUHQ==";
      };
    };
    "find-my-way-2.2.5" = {
      name = "find-my-way";
      packageName = "find-my-way";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-my-way/-/find-my-way-2.2.5.tgz";
        sha512 = "GjRZZlGcGmTh9t+6Xrj5K0YprpoAFCAiCPgmAH9Kb09O4oX6hYuckDfnDipYj+Q7B1GtYWSzDI5HEecNYscLQg==";
      };
    };
    "follow-redirects-1.13.1" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.13.1.tgz";
        sha512 = "SSG5xmZh1mkPGyKzjZP8zLjltIfpW32Y5QpdNJyjcfGxK3qo3NDDkZOZSFiGn1A6SclQxY9GzEwAHQ3dmYRWpg==";
      };
    };
    "formidable-1.2.2" = {
      name = "formidable";
      packageName = "formidable";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/formidable/-/formidable-1.2.2.tgz";
        sha512 = "V8gLm+41I/8kguQ4/o1D3RIHRmhYFG4pnNyonvua+40rqcEmT4+V71yaZ3B457xbbgCsCfjSPi65u/W6vK1U5Q==";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha1 = "3d8cadd90d976569fa835ab1f8e4b23a105605a7";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "glob-6.0.4" = {
      name = "glob";
      packageName = "glob";
      version = "6.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-6.0.4.tgz";
        sha1 = "0f08860f6a155127b2fadd4f9ce24b1aab6e4d22";
      };
    };
    "handle-thing-2.0.1" = {
      name = "handle-thing";
      packageName = "handle-thing";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/handle-thing/-/handle-thing-2.0.1.tgz";
        sha512 = "9Qn4yBxelxoh2Ow62nP+Ka/kMnOXRi8BXnRaUwezLNhqelnN49xKz4F/dPP8OYLxLxq6JDtZb2i9XznUQbNPTg==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "hpack.js-2.1.6" = {
      name = "hpack.js";
      packageName = "hpack.js";
      version = "2.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/hpack.js/-/hpack.js-2.1.6.tgz";
        sha1 = "87774c0949e513f42e84575b3c45681fade2a0b2";
      };
    };
    "http-deceiver-1.2.7" = {
      name = "http-deceiver";
      packageName = "http-deceiver";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-deceiver/-/http-deceiver-1.2.7.tgz";
        sha1 = "fa7168944ab9a519d337cb0bec7284dc3e723d87";
      };
    };
    "http-errors-1.6.3" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.6.3.tgz";
        sha1 = "8b55680bb4be283a0b5bf4ea2e38580be1d9320d";
      };
    };
    "http-signature-1.3.4" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.3.4.tgz";
        sha512 = "CbG3io8gUSIxNNSgq+XMjgpTMzAeVRipxVXjuGrDhH5M1a2kZ03w20s8FCLR1NjnnJj10KbvabvckmtQcYNb9g==";
      };
    };
    "https-proxy-agent-5.0.0" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.0.tgz";
        sha512 = "EkYm5BcKUGiduxzSt3Eppko+PiNWNEpa4ySk9vTC6wDsQJW9rHSa+UhGNJoRYp7bz6Ht1eaRIa6QaJqO5rCFbA==";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "inquirer-7.3.3" = {
      name = "inquirer";
      packageName = "inquirer";
      version = "7.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inquirer/-/inquirer-7.3.3.tgz";
        sha512 = "JG3eIAj5V9CwcGvuOmoo6LB9kbAYT8HXffUl6memuszlwDC/qvFAJw49XJ5NROSFNPxp3iQg1GqkFhaY/CR0IA==";
      };
    };
    "ip-address-6.4.0" = {
      name = "ip-address";
      packageName = "ip-address";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-address/-/ip-address-6.4.0.tgz";
        sha512 = "c5uxc2WUTuRBVHT/6r4m7HIr/DfV0bF6DvLH3iZGSK8wp8iMwwZSgIq2do0asFf8q9ECug0SE+6+1ACMe4sorA==";
      };
    };
    "ip-sub-1.0.19" = {
      name = "ip-sub";
      packageName = "ip-sub";
      version = "1.0.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-sub/-/ip-sub-1.0.19.tgz";
        sha512 = "kDjWkCvq7EID99B0GHDZUGoDrLz6Oebe2sL9yV8Wc2M8rnT5V00/yhuADoOZi8AR2gDbNT+aBWGSQhihiGSGzg==";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "js-yaml-3.14.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.1.tgz";
        sha512 = "okMH7OXXJ7YrN9Ok3/SXrnu4iX9yOk+25nqX4imS2npuvTYDmo/QEZoqwZkYaIDk3jVvBOTOIEgEhaLOynBS9g==";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "jsbn-1.1.0" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-1.1.0.tgz";
        sha1 = "b01307cb29b618a1ed26ec79e911f803c4da0040";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "kafkajs-1.15.0" = {
      name = "kafkajs";
      packageName = "kafkajs";
      version = "1.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kafkajs/-/kafkajs-1.15.0.tgz";
        sha512 = "yjPyEnQCkPxAuQLIJnY5dI+xnmmgXmhuOQ1GVxClG5KTOV/rJcW1qA3UfvyEJKTp/RTSqQnUR3HJsKFvHyTpNg==";
      };
    };
    "lodash-4.17.19" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.19.tgz";
        sha512 = "JNvd8XER9GQX0v2qJgsaN/mzFCNA5BRe/j8JN9d+tWyGLSodKQHKFicdwNYzWwI3wjRnaKPsGj1XkBjx/F96DQ==";
      };
    };
    "lodash.find-4.6.0" = {
      name = "lodash.find";
      packageName = "lodash.find";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.find/-/lodash.find-4.6.0.tgz";
        sha1 = "cb0704d47ab71789ffa0de8b97dd926fb88b13b1";
      };
    };
    "lodash.max-4.0.1" = {
      name = "lodash.max";
      packageName = "lodash.max";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.max/-/lodash.max-4.0.1.tgz";
        sha1 = "8735566c618b35a9f760520b487ae79658af136a";
      };
    };
    "lodash.merge-4.6.2" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.2.tgz";
        sha512 = "0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==";
      };
    };
    "lodash.padstart-4.6.1" = {
      name = "lodash.padstart";
      packageName = "lodash.padstart";
      version = "4.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.padstart/-/lodash.padstart-4.6.1.tgz";
        sha1 = "d2e3eebff0d9d39ad50f5cbd1b52a7bce6bb611b";
      };
    };
    "lodash.repeat-4.1.0" = {
      name = "lodash.repeat";
      packageName = "lodash.repeat";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.repeat/-/lodash.repeat-4.1.0.tgz";
        sha1 = "fc7de8131d8c8ac07e4b49f74ffe829d1f2bec44";
      };
    };
    "lru-cache-5.1.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-5.1.1.tgz";
        sha512 = "KpNARQA3Iwv+jTA0utUVVbrh+Jlrr1Fv0e56GGzAFOXN7dk/FviaDW8LHmK52DlcH4WP2n6gI8vN1aesBFgo9w==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "lru_map-0.3.3" = {
      name = "lru_map";
      packageName = "lru_map";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru_map/-/lru_map-0.3.3.tgz";
        sha1 = "b5c8351b9464cbd750335a79650a0ec0e56118dd";
      };
    };
    "md5-2.3.0" = {
      name = "md5";
      packageName = "md5";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5/-/md5-2.3.0.tgz";
        sha512 = "T1GITYmFaKuO91vxyoQMFETst+O71VUPEU3ze5GNzDm0OWdP8v1ziTaAEPUr/3kLsY3Sftgz242A1SetQiDL7g==";
      };
    };
    "mime-1.4.1" = {
      name = "mime";
      packageName = "mime";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.4.1.tgz";
        sha512 = "KI1+qOZu5DcW6wayYHSzR/tXKCDC5Om4s1z2QJjDULzLcmf3DvzS7oluY4HCTrc+9FiKmWUgeNLg7W3uIQvxtQ==";
      };
    };
    "mime-2.4.6" = {
      name = "mime";
      packageName = "mime";
      version = "2.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-2.4.6.tgz";
        sha512 = "RZKhC3EmpBchfTGBVb8fb+RL2cWyw/32lshnsETttkBAyAUXSGHxbEJWWRXc751DrIxG1q04b8QwMbAwkRPpUA==";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "minimalistic-assert-1.0.1" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz";
        sha512 = "UtJcAD4yEaGtjPezWuO9wC4nwUnVH/8/Im3yEHQP4b67cXlD/Qr9hdITCU1xDbSEXg2XKNaP8jsReV7vQd00/A==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "mixme-0.3.5" = {
      name = "mixme";
      packageName = "mixme";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mixme/-/mixme-0.3.5.tgz";
        sha512 = "SyV9uPETRig5ZmYev0ANfiGeB+g6N2EnqqEfBbCGmmJ6MgZ3E4qv5aPbnHVdZ60KAHHXV+T3sXopdrnIXQdmjQ==";
      };
    };
    "mkdirp-0.5.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.5.tgz";
        sha512 = "NKmAlESf6jMGym1++R0Ra7wvhV+wFW63FaSOFPwRahvea0gMUcGUhVeAg/0BC0wiv9ih5NYPB1Wn1UEI1/L+xQ==";
      };
    };
    "moment-2.29.1" = {
      name = "moment";
      packageName = "moment";
      version = "2.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.29.1.tgz";
        sha512 = "kHmoybcPV8Sqy59DwNDY3Jefr64lK/by/da0ViFcuA4DH0vQg5Q6Ze5VimxkfQNSC+Mls/Kx53s7TjP1RhFEDQ==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "mute-stream-0.0.8" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.8.tgz";
        sha512 = "nnbWWOkoWyUsTjKrhgD0dcz22mdkSnpYqbEjIm2nhwhuxlSkpywJmBo8h0ZqJdkp73mb90SssHkN4rsRaBAfAA==";
      };
    };
    "mv-2.1.1" = {
      name = "mv";
      packageName = "mv";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mv/-/mv-2.1.1.tgz";
        sha1 = "ae6ce0d6f6d5e0a4f7d893798d03c1ea9559b6a2";
      };
    };
    "nan-2.14.1" = {
      name = "nan";
      packageName = "nan";
      version = "2.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.14.1.tgz";
        sha512 = "isWHgVjnFjh2x2yuJ/tj3JbwoHu3UC2dX5G/88Cm24yB6YopVgxvBObDY7n5xW6ExmFhJpSEQqFPvq9zaXc8Jw==";
      };
    };
    "ncp-2.0.0" = {
      name = "ncp";
      packageName = "ncp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ncp/-/ncp-2.0.0.tgz";
        sha1 = "195a21d6c46e361d2fb1281ba38b91e9df7bdbb3";
      };
    };
    "negotiator-0.6.2" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.2.tgz";
        sha512 = "hZXc7K2e+PgeI1eDBe/10Ard4ekbfrrqG8Ep+8Jmf4JID2bNg7NvCPOZN+kfF574pFQI7mum2AUqDidoKqcTOw==";
      };
    };
    "node-gyp-build-4.2.3" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.2.3.tgz";
        sha512 = "MN6ZpzmfNCRM+3t57PTJHgHyw/h4OWnZ6mR8P5j/uZtqQr46RRuDE/P+g3n0YR/AiYXeWixZZzaip77gdICfRg==";
      };
    };
    "nodemailer-6.4.16" = {
      name = "nodemailer";
      packageName = "nodemailer";
      version = "6.4.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/nodemailer/-/nodemailer-6.4.16.tgz";
        sha512 = "68K0LgZ6hmZ7PVmwL78gzNdjpj5viqBdFqKrTtr9bZbJYj6BRj5W6WGkxXrEnUl3Co3CBXi3CZBUlpV/foGnOQ==";
      };
    };
    "obuf-1.1.2" = {
      name = "obuf";
      packageName = "obuf";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/obuf/-/obuf-1.1.2.tgz";
        sha512 = "PX1wu0AmAdPqOL1mWhqmlOd8kOIZQwGZw6rh7uby9fTc5lhaOWFLX3I6R1hrF9k3zUY40e6igsLGkDXK92LJNg==";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "onetime-5.1.2" = {
      name = "onetime";
      packageName = "onetime";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
        sha512 = "kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "path-0.12.7" = {
      name = "path";
      packageName = "path";
      version = "0.12.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path/-/path-0.12.7.tgz";
        sha1 = "d4dc2a506c4ce2197eb481ebfcd5b36c0140b10f";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "pidusage-2.0.20" = {
      name = "pidusage";
      packageName = "pidusage";
      version = "2.0.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/pidusage/-/pidusage-2.0.20.tgz";
        sha512 = "ObZwSCGhHAu+fDpHeIP7ZTy5YbQNOguJCKQE02kSnlEvBgj62cParJ4nzYQxpXauKUzT3e0CeSb1Y9Cgbry2qQ==";
      };
    };
    "process-0.11.10" = {
      name = "process";
      packageName = "process";
      version = "0.11.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
        sha1 = "7332300e840161bda3e69a1d1d91a7d4bc16f182";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "qs-6.9.4" = {
      name = "qs";
      packageName = "qs";
      version = "6.9.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.9.4.tgz";
        sha512 = "A1kFqHekCTM7cz0udomYUoYNWjBebHm/5wzU/XqrBRBNWectVH0QIiN+NEcZ0Dte5hvzHwbr8+XQmguPhJ6WdQ==";
      };
    };
    "radix-trie-js-1.0.5" = {
      name = "radix-trie-js";
      packageName = "radix-trie-js";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/radix-trie-js/-/radix-trie-js-1.0.5.tgz";
        sha512 = "3Olqy+P8cM5G2x+mnhD231bRM8c2uxAyU7uLS/dORgwzmr2CJKhT6DeQGqZyjsfWuqCYeX415xlMr1J6Xt7M9Q==";
      };
    };
    "range-parser-1.2.1" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.1.tgz";
        sha512 = "Hrgsx+orqoygnmhFbKaHE6c296J+HTAQXoxEF6gNupROmmGJRoyzfG3ccAveqCBrwr/2yxQ5BVd/GTl5agOwSg==";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha1 = "8c64ad5fd30dab1c976e2344ffe7f792a6a6df42";
      };
    };
    "restify-8.5.1" = {
      name = "restify";
      packageName = "restify";
      version = "8.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/restify/-/restify-8.5.1.tgz";
        sha512 = "g+xciouvSDg2vmCZuCinztt2mvQynCfnGIE1y8vMjfcUrjBo4AP8DJ9RNheu0mdGpiI0cMoCHYA/GdZ3TEW+DA==";
      };
    };
    "restify-errors-8.0.2" = {
      name = "restify-errors";
      packageName = "restify-errors";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/restify-errors/-/restify-errors-8.0.2.tgz";
        sha512 = "UsXUVQo7M26xoQzeUcZQ0+H8L2t9DGzrXcAgR3WB/1vnbl+UdI4tZ1PqYsN+sS5WnqHKZ0Xy9w0CKf83bbrwYA==";
      };
    };
    "restore-cursor-3.1.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-3.1.0.tgz";
        sha512 = "l+sSefzHpj5qimhFSE5a8nufZYAM3sBSVMAPtYkmC+4EH2anSGaEMXSD0izRQbu9nfyQ9y5JrVmp7E8oZrUjvA==";
      };
    };
    "ret-0.2.2" = {
      name = "ret";
      packageName = "ret";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ret/-/ret-0.2.2.tgz";
        sha512 = "M0b3YWQs7R3Z917WRQy1HHA7Ba7D8hvZg6UE5mLykJxQVE2ju0IXbGlaHPPlkY+WN7wFP+wUMXmBFA0aV6vYGQ==";
      };
    };
    "rimraf-2.4.5" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.4.5.tgz";
        sha1 = "ee710ce5d93a8fdb856fb5ea8ff0e2d75934b2da";
      };
    };
    "rpki-validator-2.2.12" = {
      name = "rpki-validator";
      packageName = "rpki-validator";
      version = "2.2.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/rpki-validator/-/rpki-validator-2.2.12.tgz";
        sha512 = "sv6MWMVmEKceha/hZdgZjghIQanI09e3j71r8pTowqAHGpq3FyRqv/WgztvfA3u5TOlCklBybifB0kz/xKW0+Q==";
      };
    };
    "run-async-2.4.1" = {
      name = "run-async";
      packageName = "run-async";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-async/-/run-async-2.4.1.tgz";
        sha512 = "tvVnVv01b8c1RrA6Ep7JkStj85Guv/YrMcwqYQnwjsAS2cTmmPGBBjAjpCW7RrSodNSoE2/qg9O4bceNvUuDgQ==";
      };
    };
    "rxjs-6.6.3" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "6.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-6.6.3.tgz";
        sha512 = "trsQc+xYYXZ3urjOiJOuCOa5N3jAZ3eiSpQB5hIT8zGlL2QfnHLJ2r7GMkBGuIausdJN1OneaI6gQlsqNHHmZQ==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safe-json-stringify-1.2.0" = {
      name = "safe-json-stringify";
      packageName = "safe-json-stringify";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-json-stringify/-/safe-json-stringify-1.2.0.tgz";
        sha512 = "gH8eh2nZudPQO6TytOvbxnuhYBOvDBBLW52tz5q6X58lJcd/tkmqFR+5Z9adS8aJtURSXWThWy/xJtJwixErvg==";
      };
    };
    "safe-regex2-2.0.0" = {
      name = "safe-regex2";
      packageName = "safe-regex2";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-regex2/-/safe-regex2-2.0.0.tgz";
        sha512 = "PaUSFsUaNNuKwkBijoAPHAK6/eM6VirvyPWlZ7BAQy4D+hCvh4B6lIG+nPdhbFfIbP+gTGBcrdsOaUs0F+ZBOQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "select-hose-2.0.0" = {
      name = "select-hose";
      packageName = "select-hose";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/select-hose/-/select-hose-2.0.0.tgz";
        sha1 = "625d8658f865af43ec962bfc376a37359a4994ca";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "semver-7.3.4" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.4.tgz";
        sha512 = "tCfb2WLjqFAtXn4KEdxIhalnRtoKFN7nAwj0B3ZXCbQloV2tq5eDbcTmT68JJD3nRJq24/XgxtQKFIpQdtvmVw==";
      };
    };
    "semver-store-0.3.0" = {
      name = "semver-store";
      packageName = "semver-store";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver-store/-/semver-store-0.3.0.tgz";
        sha512 = "TcZvGMMy9vodEFSse30lWinkj+JgOBvPn8wRItpQRSayhc+4ssDs335uklkfvQQJgL/WvmHLVj4Ycv2s7QCQMg==";
      };
    };
    "send-0.16.2" = {
      name = "send";
      packageName = "send";
      version = "0.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.16.2.tgz";
        sha512 = "E64YFPUssFHEFBvpbbjr44NCLtI1AohxQ8ZSiJjQLskAdKuriYEP6VyGEsRDH8ScozGpkaX1BGvhanqCwkcEZw==";
      };
    };
    "setprototypeof-1.1.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.0.tgz";
        sha512 = "BvE/TwpZX4FXExxOxZyRGQQv651MSwmWKZGqvmPcRIjDqWub67kTKuIMx43cZZrS/cBBzwBcNDWoFxt2XEFIpQ==";
      };
    };
    "signal-exit-3.0.3" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.3.tgz";
        sha512 = "VUJ49FC8U1OxwZLxIbTTrDvLnf/6TDgxZcK8wxR8zs13xpx7xbG60ndBlhNrFi2EMuFRoeDoJO7wthSLq42EjA==";
      };
    };
    "spdy-4.0.2" = {
      name = "spdy";
      packageName = "spdy";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdy/-/spdy-4.0.2.tgz";
        sha512 = "r46gZQZQV+Kl9oItvl1JZZqJKGr+oEkB08A6BzkiR7593/7IbtuncXHd2YoYeTsG4157ZssMu9KYvUHLcjcDoA==";
      };
    };
    "spdy-transport-3.0.0" = {
      name = "spdy-transport";
      packageName = "spdy-transport";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdy-transport/-/spdy-transport-3.0.0.tgz";
        sha512 = "hsLVFE5SjA6TCisWeJXFKniGGOpBgMLmerfO2aCyCU5s7nJ/rpAepqmFifv/GCbSbueEeAJJnmSQ2rKC/g8Fcw==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "sprintf-js-1.1.2" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.2.tgz";
        sha512 = "VE0SOVEHCk7Qc8ulkWw3ntAzXuqf7S2lvwQaDLRnUeIEaKNQJzV6BwmLKhOqT61aGhfUMrXeaBk+oDGCzvhcug==";
      };
    };
    "sshpk-1.16.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.16.1.tgz";
        sha512 = "HXXqVUq7+pcKeLqqZj6mHFUMvXtOJt1uoUx09pFW6011inTMxqI8BA8PM95myrIyyKwdnzjdFjLiE6KBPVtJIg==";
      };
    };
    "statuses-1.4.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.4.0.tgz";
        sha512 = "zhSCtt8v2NDrRlPQpCNtw/heZLtfUDqxBM1udqikb/Hbk52LK4nQSwr10u77iopCW5LsyHpuXS0GnEc48mLeew==";
      };
    };
    "stream-transform-2.0.2" = {
      name = "stream-transform";
      packageName = "stream-transform";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-transform/-/stream-transform-2.0.2.tgz";
        sha512 = "J+D5jWPF/1oX+r9ZaZvEXFbu7znjxSkbNAHJ9L44bt/tCVuOEWZlDqU9qJk7N2xBU1S+K2DPpSKeR/MucmCA1Q==";
      };
    };
    "string-width-4.2.0" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.0.tgz";
        sha512 = "zUz5JD+tgqtuDjMhwIg5uFVV3dtqZ9yQJlZVfq4I01/K5Paj5UHj7VyrQOJvzawSVlKpObApbfD0Ed6yJc+1eg==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "strip-ansi-6.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.0.tgz";
        sha512 = "AuvKTrTfQNYNIctbR1K/YGTR1756GycPsg7b9bdV9Duqur4gv6aKqHXah67Z8ImS7WEz5QVcOtlfW2rZEugt6w==";
      };
    };
    "supports-color-7.1.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.1.0.tgz";
        sha512 = "oRSIpR8pxT1Wr2FquTNnGet79b3BWljqOuoW/h4oBhxJ/HUbX5nX6JSruTkvXDCFMwDPvsaTTbvMLKZWSy0R5g==";
      };
    };
    "syslog-client-1.1.1" = {
      name = "syslog-client";
      packageName = "syslog-client";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/syslog-client/-/syslog-client-1.1.1.tgz";
        sha1 = "bdb28de3b5b7eb28a11352ec3eb78e55aed2ab6b";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "tmp-0.0.33" = {
      name = "tmp";
      packageName = "tmp";
      version = "0.0.33";
      src = fetchurl {
        url = "https://registry.npmjs.org/tmp/-/tmp-0.0.33.tgz";
        sha512 = "jRCJlojKnZ3addtTOjdIqoRuPEKBvNXcGYqzO6zWZX8KfKEpnGY5jfggJQ3EjKuu8D4bJRr0y+cYJFmYbImXGw==";
      };
    };
    "tslib-1.13.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.13.0.tgz";
        sha512 = "i/6DQjL8Xf3be4K/E6Wgpekn5Qasl1usyw++dAA35Ue5orEn65VIxOA+YvNNl9HV3qv70T7CNwjODHZrLwvd1Q==";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "type-fest-0.11.0" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-0.11.0.tgz";
        sha512 = "OdjXJxnCN1AvyLSzeKIgXTXxV+99ZuXl3Hpo9XpJAv9MBcHrrJOQ5kV7ypXOuQie+AmWG25hLbiKdwYTifzcfQ==";
      };
    };
    "utf-8-validate-5.0.3" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-5.0.3.tgz";
        sha512 = "jtJM6fpGv8C1SoH4PtG22pGto6x+Y8uPprW0tw3//gGFhDDTiuksgradgFN6yRayDP4SyZZa6ZMGHLIa17+M8A==";
      };
    };
    "util-0.10.4" = {
      name = "util";
      packageName = "util";
      version = "0.10.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.4.tgz";
        sha512 = "0Pm9hTQ3se5ll1XihRic3FDIku70C+iHUdT/W926rSgHV5QgXsYbKZN8MSC3tJtSkhuROzvsQjAaFENRXr+19A==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "uuid-3.4.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz";
        sha512 = "HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==";
      };
    };
    "vasync-2.2.0" = {
      name = "vasync";
      packageName = "vasync";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vasync/-/vasync-2.2.0.tgz";
        sha1 = "cfde751860a15822db3b132bc59b116a4adaf01b";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "wbuf-1.7.3" = {
      name = "wbuf";
      packageName = "wbuf";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wbuf/-/wbuf-1.7.3.tgz";
        sha512 = "O84QOnr0icsbFGLS0O3bI5FswxzRr8/gHwWkDlQFskhSPryQXvrTMxjxGP4+iWYoauLoBvfDpkrOauZ+0iZpDA==";
      };
    };
    "wrap-ansi-7.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-7.4.1" = {
      name = "ws";
      packageName = "ws";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.4.1.tgz";
        sha512 = "pTsP8UAfhy3sk1lSk/O/s4tjD0CRwvMnzvwr4OKGX7ZvqZtUyx4KIJB5JWbkykPoc55tixMGgTNoh3k4FkNGFQ==";
      };
    };
    "y18n-5.0.5" = {
      name = "y18n";
      packageName = "y18n";
      version = "5.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-5.0.5.tgz";
        sha512 = "hsRUr4FFrvhhRH12wOdfs38Gy7k2FFzB9qgN9v3aLykRq0dRcdcpz5C9FxdS2NuhOrI/628b/KSTJ3rwHysYSg==";
      };
    };
    "yallist-3.1.1" = {
      name = "yallist";
      packageName = "yallist";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-3.1.1.tgz";
        sha512 = "a4UGQaWPH59mOXUYnAG2ewncQS4i4F43Tv3JoAM+s2VDAmS9NsK8GpDMLrCHPksFT7h3K6TOoUNn2pb7RoXx4g==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yargs-16.2.0" = {
      name = "yargs";
      packageName = "yargs";
      version = "16.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-16.2.0.tgz";
        sha512 = "D1mvvtDG0L5ft/jGWkLpG1+m0eQxOfaBvTNELraWj22wSVUMWxZUvYgJYcKh6jGGIkJFhH4IZPQhR4TKpc8mBw==";
      };
    };
    "yargs-parser-20.2.4" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "20.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-20.2.4.tgz";
        sha512 = "WOkpgNhPTlE73h4VFAFsOnomJVaovO8VqLDzy5saChRBFQFBoMYirowyW+Q9HB4HFF4Z7VZTiG3iSzJJA29yRA==";
      };
    };
  };
  args = {
    name = "bgpalerter";
    packageName = "bgpalerter";
    version = "1.27.1";
    src = ./.;
    dependencies = [
      (sources."@netflix/nerror-1.1.3" // {
        dependencies = [
          sources."extsprintf-1.4.0"
        ];
      })
      sources."@sentry/core-5.29.0"
      sources."@sentry/hub-5.29.0"
      sources."@sentry/minimal-5.29.0"
      sources."@sentry/node-5.29.0"
      sources."@sentry/tracing-5.29.0"
      sources."@sentry/types-5.29.0"
      sources."@sentry/utils-5.29.0"
      sources."@types/color-name-1.1.1"
      sources."ansi-escapes-4.3.1"
      sources."ansi-regex-5.0.0"
      sources."ansi-styles-4.2.1"
      (sources."argparse-1.0.10" // {
        dependencies = [
          sources."sprintf-js-1.0.3"
        ];
      })
      sources."asn1-0.2.4"
      sources."assert-plus-1.0.0"
      sources."axios-0.21.1"
      sources."balanced-match-1.0.0"
      sources."batch-promises-0.0.3"
      sources."bcrypt-pbkdf-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."brembo-2.0.4"
      sources."bufferutil-4.0.2"
      sources."bunyan-1.8.12"
      sources."chardet-0.7.0"
      sources."charenc-0.0.2"
      sources."cli-cursor-3.1.0"
      sources."cli-width-3.0.0"
      sources."cliui-7.0.4"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."concat-map-0.0.1"
      sources."cookie-0.4.1"
      sources."core-util-is-1.0.2"
      sources."crypt-0.0.2"
      sources."csv-5.3.2"
      sources."csv-generate-3.2.4"
      sources."csv-parse-4.10.1"
      sources."csv-stringify-5.5.0"
      sources."dashdash-1.14.1"
      sources."debug-4.1.1"
      sources."deepmerge-4.2.2"
      sources."depd-1.1.2"
      sources."destroy-1.0.4"
      sources."detect-node-2.0.4"
      sources."dtrace-provider-0.8.8"
      (sources."ecc-jsbn-0.1.2" // {
        dependencies = [
          sources."jsbn-0.1.1"
        ];
      })
      sources."ee-first-1.1.1"
      sources."emoji-regex-8.0.0"
      sources."encodeurl-1.0.2"
      sources."escalade-3.1.1"
      sources."escape-html-1.0.3"
      sources."escape-regexp-component-1.0.2"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.1"
      sources."etag-1.8.1"
      sources."ewma-2.0.1"
      sources."external-editor-3.1.0"
      sources."extsprintf-1.3.0"
      sources."fast-decode-uri-component-1.0.1"
      sources."figures-3.2.0"
      sources."file-stream-rotator-0.5.7"
      sources."find-my-way-2.2.5"
      sources."follow-redirects-1.13.1"
      sources."formidable-1.2.2"
      sources."fresh-0.5.2"
      sources."get-caller-file-2.0.5"
      sources."getpass-0.1.7"
      sources."glob-6.0.4"
      sources."handle-thing-2.0.1"
      sources."has-flag-4.0.0"
      sources."hpack.js-2.1.6"
      sources."http-deceiver-1.2.7"
      (sources."http-errors-1.6.3" // {
        dependencies = [
          sources."inherits-2.0.3"
        ];
      })
      sources."http-signature-1.3.4"
      (sources."https-proxy-agent-5.0.0" // {
        dependencies = [
          sources."agent-base-6.0.0"
        ];
      })
      sources."iconv-lite-0.4.24"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      (sources."inquirer-7.3.3" // {
        dependencies = [
          sources."chalk-4.1.0"
        ];
      })
      sources."ip-address-6.4.0"
      sources."ip-sub-1.0.19"
      sources."is-buffer-1.1.6"
      sources."is-fullwidth-code-point-3.0.0"
      sources."isarray-1.0.0"
      sources."js-yaml-3.14.1"
      sources."jsbn-1.1.0"
      sources."json-schema-0.2.3"
      sources."jsprim-1.4.1"
      sources."kafkajs-1.15.0"
      sources."lodash-4.17.19"
      sources."lodash.find-4.6.0"
      sources."lodash.max-4.0.1"
      sources."lodash.merge-4.6.2"
      sources."lodash.padstart-4.6.1"
      sources."lodash.repeat-4.1.0"
      sources."lru-cache-5.1.1"
      sources."lru_map-0.3.3"
      sources."md5-2.3.0"
      sources."mime-2.4.6"
      sources."mimic-fn-2.1.0"
      sources."minimalistic-assert-1.0.1"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.5"
      sources."mixme-0.3.5"
      sources."mkdirp-0.5.5"
      sources."moment-2.29.1"
      sources."ms-2.1.2"
      sources."mute-stream-0.0.8"
      sources."mv-2.1.1"
      sources."nan-2.14.1"
      sources."ncp-2.0.0"
      sources."negotiator-0.6.2"
      sources."node-gyp-build-4.2.3"
      sources."nodemailer-6.4.16"
      sources."obuf-1.1.2"
      sources."on-finished-2.3.0"
      sources."once-1.4.0"
      sources."onetime-5.1.2"
      sources."os-tmpdir-1.0.2"
      sources."path-0.12.7"
      sources."path-is-absolute-1.0.1"
      sources."pidusage-2.0.20"
      sources."process-0.11.10"
      sources."process-nextick-args-2.0.1"
      sources."qs-6.9.4"
      sources."radix-trie-js-1.0.5"
      sources."range-parser-1.2.1"
      (sources."readable-stream-2.3.7" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."require-directory-2.1.1"
      (sources."restify-8.5.1" // {
        dependencies = [
          sources."semver-6.3.0"
        ];
      })
      sources."restify-errors-8.0.2"
      sources."restore-cursor-3.1.0"
      sources."ret-0.2.2"
      sources."rimraf-2.4.5"
      sources."rpki-validator-2.2.12"
      sources."run-async-2.4.1"
      sources."rxjs-6.6.3"
      sources."safe-buffer-5.2.1"
      sources."safe-json-stringify-1.2.0"
      sources."safe-regex2-2.0.0"
      sources."safer-buffer-2.1.2"
      sources."select-hose-2.0.0"
      (sources."semver-7.3.4" // {
        dependencies = [
          sources."lru-cache-6.0.0"
          sources."yallist-4.0.0"
        ];
      })
      sources."semver-store-0.3.0"
      (sources."send-0.16.2" // {
        dependencies = [
          sources."debug-2.6.9"
          sources."mime-1.4.1"
          sources."ms-2.0.0"
        ];
      })
      sources."setprototypeof-1.1.0"
      sources."signal-exit-3.0.3"
      sources."spdy-4.0.2"
      (sources."spdy-transport-3.0.0" // {
        dependencies = [
          sources."readable-stream-3.6.0"
        ];
      })
      sources."sprintf-js-1.1.2"
      (sources."sshpk-1.16.1" // {
        dependencies = [
          sources."jsbn-0.1.1"
        ];
      })
      sources."statuses-1.4.0"
      sources."stream-transform-2.0.2"
      sources."string-width-4.2.0"
      (sources."string_decoder-1.1.1" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."strip-ansi-6.0.0"
      sources."supports-color-7.1.0"
      sources."syslog-client-1.1.1"
      sources."through-2.3.8"
      sources."tmp-0.0.33"
      sources."tslib-1.13.0"
      sources."tweetnacl-0.14.5"
      sources."type-fest-0.11.0"
      sources."utf-8-validate-5.0.3"
      (sources."util-0.10.4" // {
        dependencies = [
          sources."inherits-2.0.3"
        ];
      })
      sources."util-deprecate-1.0.2"
      sources."uuid-3.4.0"
      sources."vasync-2.2.0"
      sources."verror-1.10.0"
      sources."wbuf-1.7.3"
      sources."wrap-ansi-7.0.0"
      sources."wrappy-1.0.2"
      sources."ws-7.4.1"
      sources."yallist-3.1.1"
      (sources."yargs-16.2.0" // {
        dependencies = [
          sources."y18n-5.0.5"
        ];
      })
      sources."yargs-parser-20.2.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Software to monitor streams of BGP data. Pre-configured for real-time detection of visibility loss, RPKI invalid announcements, hijacks, and more.";
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}